### ISSUE TITLE
Mising exe from the 1.2.6 release?

### ISSUE THREAD

**Issue by danpejobo** [Durtur/Dungeoneer#107]
Hi.

Great work! Looks amazing and i thought about trying it out! 

But, is there a missing exe from the latest release, or how/where do i get the exe?

**Comment by Durtur** [comment]
Hey, yes seems like the automated build has started to fail. I added a build for windows in the release: https://github.com/Durtur/Dungeoneer/releases/download/v1.2.6/Dungeoneer.Setup.1.2.6.exe
