### ISSUE TITLE
DnDBeyond character query

### ISSUE THREAD

**Issue by Durtur** [Durtur/Dungeoneer#20]
Add option to fetch character info from a DnDBeyond character sheet. Only do this if there's alot of interest for it.

**Comment by bozhich** [comment]
Looking forward to get this

---
No "vote up" option or anythin to add interest to the feature so.. commening

**Comment by neryun** [comment]
I would be very interested

**Comment by Durtur** [comment]
I've been having a little trouble with this as DnDBeyond doesn't exactly have a good api to fetch this, but I'll see if I can get a workaround going :)

**Comment by StumbleRunner** [comment]
If you're still gauging interest, I'd like this as a feature as well.

**Comment by Durtur** [comment]
included in 1.1.2
