### ISSUE TITLE
Relative layer positioning

### ISSUE THREAD

**Issue by Bazzatron19** [Durtur/Dungeoneer#21]
It's great that we can set foreground and background images - and the scrolling features is ace.
Would be great if we could offset the origin of the foreground relative to the background.

In the below example, I've pulled some random images from google just to illustrate the problem/use case.

![image](https://user-images.githubusercontent.com/53759374/116145283-0b22b180-a6d5-11eb-921a-a20de4663584.png)

**Comment by Durtur** [comment]
@Bazzatron19  you can shift the foreground by holding down shift and pressing the arrow keys. I could maybe add a button that puts the foreground in the center of the background

**Comment by Durtur** [comment]
@Bazzatron19  or maybe a better solution is Shift + Mouse drag moves the foreground

**Comment by Durtur** [comment]
Added a center on background button for foreground
