### ISSUE TITLE
Imported tokens are always imported rotated clockwise.

### ISSUE THREAD

**Issue by Bazzatron19** [Durtur/Dungeoneer#25]
Seems that the default position of the token is always rotated 90 degrees clockwise.
could this be amended to display so that they're imported right side up?

![image](https://user-images.githubusercontent.com/53759374/116152653-16c6a600-a6de-11eb-8bca-cf76f5b34830.png)

**Comment by Durtur** [comment]
added setting for default rotation in settings window
