### ISSUE TITLE
Nonfree LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Durtur/Dungeoneer#33]
Nice tool!  If you are trying to build a community around your project, I would advise using a free software or free culture `LICENSE`.  CC ND is a nonfree license that prevents modifying the work and sharing the modifications.

I would recommend GPL-3.0-or-later or AGPL-3.0-or-later.  If sticking with Creative Commons, I would suggest [Creative Commons Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/).

**Comment by Durtur** [comment]
Replaced license with AGPL-3.0-or-later :)
