### ISSUE TITLE
Linux support (or at least partial support)

### ISSUE THREAD

**Issue by BlueDrink9** [Durtur/Dungeoneer#42]
Hello! I'm running this on linux, and while basic things work fine, like the dice rolls and item look-ups, the majority of UI elements have bugs. If you're ok with giving me a bit of extra time, I'd love to help get things working under Linux. The main thing at this stage that I'd like to use is the map tool, but no elements are visible, and clicking "image" for backgrounds does nothing.

`yarn install` returns two errors about packaging, but `yarn start` opens the window without issue.

```
info dmg-license@1.0.9: The platform "linux" is incompatible with this module.
info "dmg-license@1.0.9" is an optional dependency and failed compatibility check
. Excluding it from installation.
info iconv-corefoundation@1.1.6: The platform "linux" is incompatible with this module.
info "iconv-corefoundation@1.1.6" is an optional dependency and failed compatibility check. Excluding it from installation.
```

Things known working:

* Dice roller
* Item lookup
* Table lookup
* Table Random roll
* Conditions
* spell lookup
* loot gold calculater
* Save roller
* Shop generator

Things known not working:

* Monster lookup
* NPC and tavern generation (empty drop-downs, except gender)
* **All map visuals, including measuring tools**

**Comment by Durtur** [comment]
Hi. Thanks for testing this out.
 
Just to clarify, you've installed npm and yarn, and are running the dev verison via yarn install && yarn start?

I'll package a linux version for you, and see if that works.

**Comment by BlueDrink9** [comment]
Yes, that is correct

**Comment by Durtur** [comment]
Ok so I've set up a Linux VM for testing and it doesn't look good, I just get a blank white screen without any errors. I guess there's a problem with a package somewhere. Meanwhile, if you'd like to investigate further you can open up dev tools with ctrl+shift+i, hopefully there's an error code somewhere that should point in the right direction

**Comment by BlueDrink9** [comment]
For the time being, I've just started using MapTool. I appreciate your effort, but don't worry about doing it for my sake if it isn't an easy fix

**Comment by Durtur** [comment]
Ok no worries. I'll try to get it up and running on Linux. I would like it to run on Linux without problems and theoretically that shouldn't be too much of a hassle.

**Comment by Durtur** [comment]
So I have figured out the faulty package and fixed some file paths (which are case sensitive on Linux). I'd be grateful if you could pull the newest version, run it and see if it works correctly. If it works, I'll create a Linux build to release.

**Comment by BlueDrink9** [comment]
My gosh, it's gorgeous! I love the default map, really nice start-up experience

**Comment by BlueDrink9** [comment]
Dragging monsters' added tokens to the map doesn't work.
Can't close the party menu without entering all player names (ie can't cancel)

**Comment by Durtur** [comment]
Thank you :)

> Dragging monsters' added tokens to the map doesn't work.

 Can you elaborate a bit on this? Are you dragging from the main app screen to the map tool? The way to add tokens is to either:
- right click on the map, selecting token and start adding
- or adding a monster, such as a bandit, into the combat tracker and pressing the "m", a + button will appear in the map to add it. In this case it will be linked to the combat tracker, it will appear dead, wounded etc. 

> Can't close the party menu without entering all player names (ie can't cancel)

I don't think this is bugged, it's some basic validation where you have to insert a character name or delete the row. This is probably strange if you have no players saved.

**Comment by BlueDrink9** [comment]
Ah, my mistake. I'll try the token thing again, although I think I tried right clicking to add and no token appeared on the map.

**Comment by BlueDrink9** [comment]
Ah, I see, you have to click outside the box to add tokens. However, I can't change the token from the placeholder. Clicking an image highlights it in the token thing, and it comes up with tokens matching "goblin". However the placed tokens don't change, even subsequent placements.

**Comment by BlueDrink9** [comment]
Adding tokens via the combat tracker works for getting tokens with images, however

**Comment by Durtur** [comment]
> Ah, I see, you have to click outside the box to add tokens. However, I can't change the token from the placeholder. Clicking an image highlights it in the token thing, and it comes up with tokens matching "goblin". However the placed tokens don't change, even subsequent placements.

Ok so even though you select the token via the green select button, the token does not change? Can you press ctrl+shift+i before you add tokens this way and see if there are any error messages?

**Comment by BlueDrink9** [comment]
I missed the green select button, my bad. Not sure how or why, maybe I had the window too small. Working brilliantly, thank you so much!

**Comment by BlueDrink9** [comment]
By default they are all sideways, is that intended?

**Comment by Durtur** [comment]
That is intended yes, I use top down tokens and wanted them facing each other. You can set the degrees of default rotation for npcs and players in the settings window

**Comment by BlueDrink9** [comment]
Awesome. Anyway, I'll let you close this if you're satisfied linux support is here. I certainly am

**Comment by Durtur** [comment]
Great, I'll close this isssue and make a Linux build :)
