### ISSUE TITLE
A "New Map" or "Delete All Walls" option would be useful

### ISSUE THREAD

**Issue by StumbleRunner** [Durtur/Dungeoneer#52]
I don't know if my workflow for setting up maps is completely not the way it was intended to be done but I'm finding that when I try to set up a new dungeon level and get rid of the old one I'm basically erasing the walls using the delete wall tool which is time consuming on for a complicated dungeon level.
My workflow for setting up a level is kinda simple:
- Load scanned map as foreground layer
- Rescale size until the grid lines up properly 
- Turn on the show visibility layer and then draw in the walls over the map
- Save map

**Comment by Durtur** [comment]
Hi. Reloading the window (Ctrl+Shift+R) resets the map state, aside from the image layers (foreground, background) so I recommend doing that if you want to reset the map. 

You can also save your scanned files with the square size included, for example: Forgotten Crypt[48x48].png. The grid will automatically resize to 48x48 squares for the image. You need to enable this feature in the settings.

**Comment by StumbleRunner** [comment]
Thanks for the info, that's a big help
