### ISSUE TITLE
[Question] 404 error in installer link

### ISSUE THREAD

**Issue by atiboti** [Durtur/Dungeoneer#53]
Hey, seen your project on reddit, I'm kind of new to github, so I hope I am doing things right, I wanted to download the latest windows installer, but it threw me to error 404. I tried to download the installer from the assets, my windows detected it as a security risk. Is this normal behavior for the setup.exe? Thank you in advance!

Edit: Forced it trough windows defender, it seems working

**Comment by Durtur** [comment]
Hi. The exe is not code signed so you will get that warning. You have the right file. The reddit link is broken, I will fix it, thanks for pointing it out :)

**Comment by atiboti** [comment]
Thank you for your reply, I am looking forward to using your project in my soon-starting campaign!

**Comment by Durtur** [comment]
Great :) feel free to open an issue if you run into any problems.

**Comment by atiboti** [comment]
Will do, thank you!
