### ISSUE TITLE
Mass-deleting homebrewed monsters.

### ISSUE THREAD

**Issue by Alcays** [Durtur/Dungeoneer#61]
Hello. Apologies in advance if this is the wrong forum to be asking these questions, I'm still very much a github rookie.

Question: I tried implementing a long list of Homebrew monsters, and accidentally ended up including all the pre-existing ones as homebrew. Is there a way to delete all the homebrew monsters without selecting them one at a time? I've tried deleting homebrew folders from the installation folder, but to little success.

Also just want to add: amazing app! It's incredibly user-friendly even for simpletons such as myself.

![image](https://user-images.githubusercontent.com/105162673/167302082-e1b11cf0-a5ec-4e51-b83a-a05b3003a911.png)

**Comment by Durtur** [comment]
The home brew is stored as json in your user data folder (appdata local roaming on windows). Look for a file called homebrew.json and delete it and you should be all set

**Comment by Durtur** [comment]
I'll close this, feel free to reopen if you have any more questions
