### ISSUE TITLE
[BUG] java script error in the main process

### ISSUE THREAD

**Issue by jeffwool** [Durtur/Dungeoneer#66]
![Dungeoneer bug](https://user-images.githubusercontent.com/48832610/177876003-5567ef49-b121-46e2-be2c-c26774bab08d.PNG)

**Comment by jeffwool** [comment]
This happens when clicking on the map tool tab

**Comment by Durtur** [comment]
Hi. Are you running the program for the first time? There seems to be a problem with the settings json file, it's located in your appdata/Dungeoneer folder. Deleting it should resolve the issue

**Comment by jeffwool** [comment]
I has only run the program once. Everything else seemed to work fine. Only
when i clicked on the map tab at the top of the window did I get an error
(the one screenshoted in the github message).
