### ISSUE TITLE
[Feature] Add support for imported sounds

### ISSUE THREAD

**Issue by Durtur** [Durtur/Dungeoneer#77]
The online client can only play sounds from the default sound library. It should be able to play sounds from the user defined sounds. 

Encode the sound and send it over webrtc in server.js, like the token images.

**Comment by 0x07C0** [comment]
Could it be a nice addition to allow adding sounds from external sources? For example using a site with `Allow-Origin: *` to serve mp3 files to the client. (like it's done with ogreforge's `docs/client/sounds`)

**Comment by Durtur** [comment]
@0x07C0 that's a good idea

**Comment by Durtur** [comment]
Implemented for 1.2.2. I'll create a new issue to support external sounds
