### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GoldenCaesar** [Durtur/Dungeoneer#82]
**Describe the bug**
When opening the player tab, if you delete all players, you are no longer able to add players until you refresh the whole application
**Expected behavior**
even if all players are deleted the 'add' button should still function

**Screenshots**

**Additional context**
sometimes it also does not allow me to close the player tab if all players are deleted until i refresh

**Comment by Durtur** [comment]
Hi, there's an issue for this and it should be fixed in the next version > https://github.com/Durtur/Dungeoneer/pull/72
