### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GoldenCaesar** [Durtur/Dungeoneer#83]
**Describe the bug**
clicking the 'add monster to map' button "m" simply takes me to an empty map, but the only way to add anything to the map is by right-clicking and creating a new token with my own image and name. 

**Expected behavior**
a placeholder image or image of the monster along with its stats should be added as a token to the map i believe is what it says in the help tab

**Screenshots**

**Additional context**

**Comment by Durtur** [comment]
When clicking the add monster to map button it should focus on or start the map window. Then you should see a large plus button to start adding the connected tokens. 

![image](https://user-images.githubusercontent.com/32142088/186507229-0be26dd1-b4f9-43e4-bce1-b3ef0040ffe4.png)

Does the + button not appear?

**Comment by Durtur** [comment]
I changed the UI a little bit to make this a little bit more obvious. Feel free to open another issue if this persists.
