### ISSUE TITLE
[BUG] Link to DnDBeyond does nothing

### ISSUE THREAD

**Issue by GoldenCaesar** [Durtur/Dungeoneer#84]
**Describe the bug**
the 'link to dndbeyond' does nothing when adding in a character sheet public link

**Expected behavior**
expected it to pull the character name and stats from the dndbeyond url

**Screenshots**

**Additional context**

**Comment by Durtur** [comment]
It looks like this is an issue when adding the link to a new character (new row). Until this is fix you can circumvent this by opening the party window, adding the character, closing the window and then add the DnDBeyond link. It should display the correct name and stats in the player plaque.s

**Comment by 0x07C0** [comment]
Oops, I'm so sorry for this spam.

**Comment by Durtur** [comment]
Fixed and added some more stuff to display
